project:
  class: Directory
  path: /home/tgirke/tmp/GEN242/content/en/tutorials/systempiper/rnaseq
data:
  class: Directory
  path: /home/tgirke/tmp/GEN242/content/en/tutorials/systempiper/rnaseq/data
param:
  class: Directory
  path: /home/tgirke/tmp/GEN242/content/en/tutorials/systempiper/rnaseq/param
results:
  class: Directory
  path: /home/tgirke/tmp/GEN242/content/en/tutorials/systempiper/rnaseq/results
targets:
  class: File
  path: targets.txt
script:
  class: File
  path: systemPipeRNAseq.Rmd
input_steps: '1:11'
